# Generated by Django 3.2.9 on 2021-11-28 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('rate', models.PositiveIntegerField()),
                ('detail', models.TextField(verbose_name='Detail')),
                ('guarantee', models.CharField(max_length=120)),
                ('is_super_offer', models.BooleanField(default=False)),
                ('is_special_offer', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('is_hot', models.BooleanField(default=False)),
                ('categtory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
