# Generated by Django 3.2.9 on 2021-12-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_categtory_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
