# Generated by Django 3.2.9 on 2021-12-13 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_rename_categtory_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('percent', models.PositiveIntegerField(default=10)),
                ('max_price', models.PositiveIntegerField(default=50000)),
                ('period', models.DateTimeField(default=django.utils.timezone.now)),
                ('reUseAble', models.BooleanField(default=False)),
                ('customers', models.ManyToManyField(blank=True, related_name='used_discounts', to=settings.AUTH_USER_MODEL)),
                ('just_for', models.ManyToManyField(blank=True, related_name='special_discount', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='discounts', to='product.Color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('count', models.PositiveIntegerField(default=1)),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('refer_code', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('p', 'process'), ('a', 'accepted'), ('s', 'send to post'), ('d', 'delivered'), ('r', 'returned')], default='p', max_length=1)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='transaction.discount')),
                ('items', models.ManyToManyField(related_name='inOrder', to='transaction.OrderItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('refer_code', models.CharField(max_length=60, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('w', 'waited'), ('s', 'success'), ('r', 'returned'), ('f', 'failed')], max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='transaction.orders')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
