# Generated by Django 3.2.9 on 2021-12-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='real_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
