# Generated by Django 3.2.9 on 2021-12-21 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211221_1857'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0002_orders_real_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('c', 'checkout'), ('f', 'finally'), ('n', 'normal')], default='n', max_length=1)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('real_price', models.PositiveIntegerField(default=0)),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_cart', to='transaction.discount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_price',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='inOrder', to='transaction.OrderItem'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('p', 'process'), ('c', 'checkout'), ('a', 'accepted'), ('s', 'send to post'), ('d', 'delivered'), ('r', 'returned')], default='p', max_length=1),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('count', models.PositiveIntegerField(default=1)),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transaction.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
