# Generated by Django 3.2.9 on 2022-01-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('p', 'process'), ('c', 'checkout'), ('a', 'accepted'), ('s', 'send to post'), ('d', 'delivered'), ('r', 'returned'), ('f', 'failed')], default='p', max_length=1),
        ),
    ]
