# Generated by Django 3.2.9 on 2022-01-14 13:48

import category.models.category
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=category.models.category.get_file_path),
        ),
    ]
