# Generated by Django 3.2.9 on 2022-01-14 13:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import setting.models.slides
import setting.models.superoff
import setting.models.titles


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0004_alter_discount_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_auto_20211221_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to=setting.models.titles.get_file_path)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlideImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to=setting.models.slides.get_file_path)),
                ('text', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('rank', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('browser_title', models.CharField(max_length=20)),
                ('seo_key_words', models.TextField()),
                ('contact_us', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to=setting.models.titles.get_file_path)),
                ('web_name', models.CharField(max_length=20)),
                ('about_us', models.TextField()),
                ('copy_rights', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=setting.models.superoff.get_file_path)),
                ('percent', models.PositiveIntegerField(default=30)),
                ('percent_image', models.ImageField(upload_to=setting.models.superoff.get_file_path)),
                ('limited', models.BooleanField(default=1)),
                ('till', models.DateTimeField(default=datetime.datetime.now)),
                ('customers', models.ManyToManyField(related_name='super_offer_used', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_super_offer', to='product.color')),
                ('transaction', models.ManyToManyField(blank=True, null=True, related_name='forSuperOffer', to='transaction.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
