# Generated by Django 3.2.9 on 2022-01-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_discount_code'),
        ('setting', '0002_auto_20220115_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superoffer',
            name='transaction',
            field=models.ManyToManyField(blank=True, related_name='forSuperOffer', to='transaction.Transaction'),
        ),
    ]
