# Generated by Django 3.2.9 on 2021-11-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_address_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
