# Generated by Django 3.2.9 on 2022-01-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comments_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('a', 'accepted'), ('w', 'waited'), ('r', 'rejected')], default='w', max_length=1),
        ),
    ]
